version: 0.2

phases:
  build:
    commands:
      # CDK Version is defaulted to 2.82.0 if not mentioned using `-c`
      - apt-get update -y && apt-get install -y net-tools
      # Network
      - bash gen-reports.sh -m network/basic-cdk 
      # Storage
      - bash gen-reports.sh -m storage/opensearch 
      # Orch
      #- bash gen-reports.sh -m orchestration/mwaa
      # Compute
      - bash gen-reports.sh -m compute/aws-batch -c 2.70.0 
      - bash gen-reports.sh -m compute/emr-serverless -c 2.83.1
      # Catalog
      - bash gen-reports.sh -m service-catalog/app-registry -c 2.70.0 # needed for solutions
      # Rosbag Image Pipeline
      - bash gen-reports.sh -m analysis/rosbag-image-pipeline -r requirements-dev.txt
      # Storage
      - bash gen-reports.sh -m core/metadata-storage
      # Integration
      - bash gen-reports.sh -m integration/ddb-to-opensearch
      - bash gen-reports.sh -m integration/opensearch-tunnel
      # Optionals
      - bash gen-reports.sh -m optionals/datalake-buckets
      # Post Processing
      - bash gen-reports.sh -m post-processing/yolo-object-detection
      - bash gen-reports.sh -m post-processing/yolop-lane-detection
      # Sensor Extraction
      - bash gen-reports.sh -m sensor-extraction/ros-to-parquet -c 2.70.0 #Breaking changes from 2.82.0
      - bash gen-reports.sh -m sensor-extraction/ros-to-png -c 2.70.0 #Breaking changes from 2.82.0
      # Invoke build-s3-dist.sh
      - echo "Starting build `date` in `pwd`"
      - chmod +x ./deployment/build-s3-dist.sh && ./deployment/build-s3-dist.sh $TEMPLATE_OUTPUT_BUCKET $DIST_OUTPUT_BUCKET $SOLUTION_NAME $VERSION
      - echo "Build completed `date`"
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'