AWSTemplateFormatVersion: 2010-09-09
Description: This stack deploys a Module specific IAM permissions

Parameters:
  DeploymentName:
    Type: String
    Description: The name of the deployment
  ModuleName:
    Type: String
    Description: The name of the Module
  RoleName:
    Type: String
    Description: The name of the IAM Role
  EksClusterAdminRoleArn:
    Type: String
    Description: Role from the EKS module with cluster admin permissions

Resources:
  Policy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - "autoscaling:DescribeAutoScalingGroups"
              - "sts:GetCallerIdentity"
            Effect: Allow
            Resource:
              - "*"
          - Sid: "AccessToPyTorchPublicECR"
            Action:
              - "ecr:DescribeRepositories"
              - "ecr:GetAuthorizationToken"
              - "ecr:GetDownloadUrlForLayer"
              - "ecr:BatchGetImage"
              - "ecr:BatchCheckLayerAvailability"
            Effect: Allow
            Resource:
              - "*"
          - Action:
              - "ecr:BatchCheckLayerAvailability"
              - "ecr:BatchGetImage"
              - "ecr:GetAuthorizationToken"
              - "ecr:CompleteLayerUpload"
              - "ecr:GetDownloadUrlForLayer"
              - "ecr:InitiateLayerUpload"
              - "ecr:PutImage"
              - "ecr:UploadLayerPart"
            Effect: Allow
            Resource:
              - !Sub "arn:aws:ecr::${AWS::AccountId}:repository/addf-${DeploymentName}*"
          - Action:
              - "s3:Create*"
              - "s3:Put*"
              - "s3:Delete*"
              - "s3:Get*"
              - "s3:List*"
            Effect: Allow
            Resource:
              - "arn:aws:s3:::cdk*"
          - Action:
              - "iam:CreatePolicy"
              - "iam:DetachRolePolicy"
              - "iam:DeletePolicy"
              - "iam:DeleteRolePolicy"
              - "iam:CreateRole"
              - "iam:DeleteRole"
              - "iam:AttachRolePolicy"
              - "iam:PutRolePolicy"
              - "iam:UpdateRole"
              - "iam:CreatePolicyVersion"
              - "iam:DeletePolicyVersion"
              - "iam:TagRole"
              - "iam:UntagRole"
              - "iam:PassRole"
            Effect: Allow
            Resource:
              - !Sub "arn:aws:iam::${AWS::AccountId}:role/addf-${DeploymentName}-${ModuleName}*"
              - !Sub "arn:aws:iam::${AWS::AccountId}:role/service-role/addf-${DeploymentName}-${ModuleName}*"
          - Effect: Allow
            Action:
              - "logs:CreateLogGroup"
              - "logs:Describe*"
              - "logs:DescribeLogGroups"
            Resource: 
            - !Sub "arn:aws:logs::${AWS::AccountId}:log-group/*"
          - Effect: Allow
            Action:
              - "iam:Get*"
              - "iam:List*"
            Resource:
              - !Sub "arn:aws:iam::${AWS::AccountId}:role/addf-${DeploymentName}*"
          - Effect: Allow
            Action:
              - ssm:GetParameter
            Resource:
              - !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/cdk-bootstrap*"
          - Effect: Allow
            Action:
              - cloudformation:*
            Resource:
              - !Sub "arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/addf-${DeploymentName}-${ModuleName}*"
          - Effect: Allow
            Action:
              - "iam:PassRole"
            Resource:
              - !Sub "arn:aws:iam::${AWS::AccountId}:role/cdk*"
          - Effect: Allow
            Action:
              - "sts:AssumeRole"
            Resource:
              - !Ref EksClusterAdminRoleArn
          - Effect: Allow
            Action:
              - "eks:ListNodegroups"
              - "eks:DescribeCluster"
            Resource:
              - !Sub "arn:aws:eks:${AWS::Region}:${AWS::AccountId}:cluster/addf-${DeploymentName}*"
          - Effect: Allow
            Action:
              - "eks:DescribeNodegroup"
            Resource:
              - !Sub "arn:aws:eks:${AWS::Region}:${AWS::AccountId}:nodegroup/addf-${DeploymentName}*"
          - Effect: Allow
            Action:
              - "autoscaling:CreateOrUpdateTags"
            Resource:
              - !Sub "arn:aws:autoscaling:${AWS::Region}:${AWS::AccountId}:autoScalingGroup:*"
        Version: 2012-10-17
      PolicyName: "addf-modulespecific-policy"
      Roles: [!Ref RoleName]
