AWSTemplateFormatVersion: 2010-09-09
Description: This stack deploys a Module specific IAM permissions

Parameters:
  # DeploymentName:
  #   Type: String
  #   Description: The name of the deployment
  # ModuleName:
  #   Type: String
  #   Description: The name of the Module
  RoleName:
    Type: String
    Description: The name of the IAM Role
  ECRRepoName:
    Type: String
    Description: The name of the ECR repository

Resources:
  Policy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action:
              - "ecr:Describe*"
              - "ecr:Get*"
              - "ecr:List*"
            Resource: "*"
          - Action:
              - "ecr:Create*"
              - "ecr:Delete*"
              - "ecr:*LayerUpload"
              - "ecr:UploadLayerPart"
              - "ecr:Batch*"
              - "ecr:Put*"
            Effect: Allow
            Resource:
              - !Sub "arn:${AWS::Partition}:ecr:${AWS::Region}:${AWS::AccountId}:repository/${ECRRepoName}"
        Version: 2012-10-17
      PolicyName: "modulespecific-policy"
      Roles: [!Ref RoleName]