name: example-dev
toolchainRegion: us-west-2
groups:
  - name: optionals
    path: manifests/example-dev/optional-modules.yaml
  - name: replication
    path: manifests/example-dev/replicator-modules.yaml
  - name: core
    path: manifests/example-dev/core-modules.yaml
  - name: prereqs
    path: manifests/example-dev/prereq-modules.yaml
  - name: examples
    path: manifests/example-dev/example-modules.yaml
  - name: rosbag
    path: manifests/example-dev/rosbag-modules.yaml
  - name: simulations
    path: manifests/example-dev/simulation-modules.yaml
  - name: integration
    path: manifests/example-dev/integration-modules.yaml
  # - name: ide
  #   path: manifests/example-dev/ide-modules.yaml
targetAccountMappings:
  - alias: primary
    accountId: 1234567890
    default: true
    parametersGlobal:
      dockerCredentialsSecret: aws-addf-docker-credentials
    regionMappings:
      - region: us-west-2
        default: true
