---
name: datalake-buckets
path: git::https://github.com/awslabs/autonomous-driving-data-framework.git//modules/optionals/datalake-buckets/?ref=main
parameters:
  - name: encryption-type
    value: SSE
  - name: retention-policy
    value: DESTROY
