AWSTemplateFormatVersion: 2010-09-09
Description: This stack deploys a Module specific IAM permissions

Parameters:
  ProjectName:
    Type: String
    Description: The name of the Project
  DeploymentName:
    Type: String
    Description: The name of the deployment
  ModuleName:
    Type: String
    Description: The name of the Module
  RoleName:
    Type: String
    Description: The name of the IAM Role
  EksClusterAdminRoleArn:
    Type: String
    Description: Role from the EKS module with cluster admin permissions

Resources:
  Policy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - "autoscaling:DescribeAutoScalingGroups"
            Effect: Allow
            Resource:
              - "*"
          - Action:
              - "sts:GetCallerIdentity"
            Effect: Allow
            Resource:
              - "*"
          - Action:
              - "iam:CreatePolicy"
              - "iam:DetachRolePolicy"
              - "iam:DeletePolicy"
              - "iam:DeleteRolePolicy"
              - "iam:CreateRole"
              - "iam:DeleteRole"
              - "iam:AttachRolePolicy"
              - "iam:PutRolePolicy"
              - "iam:UpdateRole"
              - "iam:CreatePolicyVersion"
              - "iam:DeletePolicyVersion"
              - "iam:TagRole"
              - "iam:UntagRole"
              - "iam:PassRole"
            Effect: Allow
            Resource:
              - !Sub "arn:aws:iam::${AWS::AccountId}:role/${ProjectName}-${DeploymentName}-${ModuleName}*"
              - !Sub "arn:aws:iam::${AWS::AccountId}:role/service-role/${ProjectName}-${DeploymentName}-${ModuleName}*"
          - Effect: Allow
            Action:
              - "logs:CreateLogGroup"
              - "logs:Describe*"
              - "logs:DescribeLogGroups"
            Resource: 
            - !Sub "arn:aws:logs::${AWS::AccountId}:log-group/*"
          - Effect: Allow
            Action:
              - "iam:Get*"
              - "iam:List*"
            Resource:
              - !Sub "arn:aws:iam::${AWS::AccountId}:role/${ProjectName}-${DeploymentName}*"
          - Effect: Allow
            Action:
              - cloudformation:*
            Resource:
              - !Sub "arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/${ProjectName}-${DeploymentName}-${ModuleName}*"
          - Effect: Allow
            Action:
              - "sts:AssumeRole"
            Resource:
              - !Ref EksClusterAdminRoleArn
          - Effect: Allow
            Action:
              - "eks:ListNodegroups"
              - "eks:DescribeCluster"
              - "eks:DescribeNodegroup"
            Resource:
              - !Sub "arn:aws:eks:${AWS::Region}:${AWS::AccountId}:cluster/${ProjectName}-${DeploymentName}*"
          - Effect: Allow
            Action:
              - "autoscaling:CreateOrUpdateTags"
            Resource:
              - !Sub "arn:aws:autoscaling:${AWS::Region}:${AWS::AccountId}:autoScalingGroup:*"
        Version: 2012-10-17
      PolicyName: "modulespecific-policy"
      Roles: [!Ref RoleName]
