name: myenv
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - awscli
  - boto3
  - ipykernel
  - torchvision
  - tqdm
  - matplotlib
  - numpy
  - scikit-image
  - readerwriterlock
  - torchmetrics
  - tensorboard
  - sagemaker-studio-image-build
