AWSTemplateFormatVersion: 2010-09-09
Description: This stack deploys a Module specific IAM permissions

Parameters:
  InstanceName:
    Type: String
    Description: The name of the Cloud9 environment
    Default: "cloud9env"
  RoleName:
    Type: String
    Description: The name of the IAM Role
Resources:
  Policy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action:
              - "ec2:CreateTags"
            Resource: "*"
          - Effect: Allow
            Action:
              - "ec2:ModifyVolume"
            Resource: "*"
            Condition:
              StringLike:
                ec2:ResourceTag/Name: !Sub 'aws-cloud9-${InstanceName}-*'
          - Effect: Allow
            Action:
              - "iam:AddRoleToInstanceProfile"
              - "iam:CreateInstanceProfile"
              - "iam:Get*"
              - "iam:RemoveRoleFromInstanceProfile"
            Resource:
              - !Sub "arn:${AWS::Partition}:iam::*:instance-profile/cloud9/AWSCloud9SSMInstanceProfile"
          - Effect: Allow
            Action:
              - "iam:AttachRolePolicy"
              - "iam:CreateRole"
              - "iam:DetachRolePolicy"
              - "iam:Get*"
              - "iam:PassRole"
              - "iam:TagRole"
            Resource:
              - !Sub "arn:${AWS::Partition}:iam::*:role/service-role/AWSCloud9SSMAccessRole"
          - Effect: Allow
            Action:
              - "ssm:GetParametersByPath"
            Resource:
              - !Sub "arn:${AWS::Partition}:ssm:*::parameter/aws/service/cloud9"
        Version: 2012-10-17
      PolicyName: "modulespecific-policy"
      Roles: [!Ref RoleName]
