apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: app
  namespace: dcv
spec:
  selector:
    matchLabels:
      env: app
  template:
    metadata:
      labels:
        env: app
    spec:
      restartPolicy: Always
      hostNetwork: true
#      serviceAccountName: dcv-agent-src-account
      containers:
        - name: app
          image: 663086445302.dkr.ecr.eu-central-1.amazonaws.com/addf-eks-viz-optionals-app-ecr:app-latest
          imagePullPolicy: "Always"
          env:
            - name: DCV_EKS_CONFIG_MAP_NAME
              value: "dcv-agent-config-map"
            - name: AWS_REGION
              value: eu-central-1
            - name: DCV_EKS_DISPLAY_PARAMETER_STORE
              value: ":0"
            - name: DISPLAY
              value: ":0"
            - name: XAUTHORITY
              value: /run/user/1000/dcv/default-session.xauth
          ports:
            - name: dcv-tcp
              protocol: TCP
              containerPort: 8443
            - name: dcv-udp
              protocol: UDP
              containerPort: 8443
          securityContext:
            privileged: true
          volumeMounts:
            - name: addf-dcv-socket-volume
              mountPath: /tmp/.X11-unix
              readOnly: false
            - name: addf-dcv-auth-volume
              mountPath: /run/user/1000/dcv
              readOnly: false
          readinessProbe:
            exec:
              command:
                - /usr/local/bin/check_healthy.sh
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 90
          livenessProbe:
            exec:
              command:
                - /usr/local/bin/check_healthy.sh
            initialDelaySeconds: 120
            periodSeconds: 10
      volumes:
        - name: addf-dcv-socket-volume
          hostPath:
            path: /tmp/x11-containers/
        - name: addf-dcv-auth-volume
          hostPath:
            path: /var/addf/dcv-eks/auth