name: dcv-k8s-deployment
path: modules/visualization/dcv-k8s-deployment
parameters:
  - name: dcv-namespace
    value: dcv
  - name: dcv-image-uri
    valueFrom:
      moduleMetadata:
        group: dcv-image
        name: dcv-image
        key: DCVImageUri
  - name: eks-cluster-admin-role-arn
    valueFrom:
      moduleMetadata:
        group: core
        name: eks
        key: EksClusterMasterRoleArn
  - name: eks-handler-role-arn
    valueFrom:
      moduleMetadata:
        group: core
        name: eks
        key: EksHandlerRoleArn
  - name: eks-cluster-name
    valueFrom:
      moduleMetadata:
        group: core
        name: eks
        key: EksClusterName
  - name: eks-oidc-arn
    valueFrom:
      moduleMetadata:
        group: core
        name: eks
        key: EksOidcArn
  - name: eks-cluster-open-id-connect-issuer
    valueFrom:
      moduleMetadata:
        group: core
        name: eks
        key: EksClusterOpenIdConnectIssuer
  - name: eks-cluster-security-group-id
    valueFrom:
      moduleMetadata:
        group: core
        name: eks
        key: EksClusterSecurityGroupId
  - name: eks-node-role-arn
    valueFrom:
      moduleMetadata:
        group: core
        name: eks
        key: EksNodeRoleArn
  - name: fsx-pvc-name
    valueFrom:
      moduleMetadata:
        group: integration
        name: lustre-on-eks
        key: PersistentVolumeClaimName