name: kubeflow-users
path: git::https://github.com/awslabs/autonomous-driving-data-framework.git//modules/mlops/kubeflow-users
parameters:
  - name: EksClusterAdminRoleArn
    valueFrom:
      moduleMetadata:
        group: core
        name: eks
        key: EksClusterAdminRoleArn
  - name: EksClusterName
    valueFrom:
      moduleMetadata:
        group: core
        name: eks
        key: EksClusterName
  - name: EksOidcArn
    valueFrom:
      moduleMetadata:
        group: core
        name: eks
        key: EksOidcArn
  - name: EksClusterOpenIdConnectIssuer
    valueFrom:
      moduleMetadata:
        group: core
        name: eks
        key: EksClusterOpenIdConnectIssuer
  # - name: KubeflowUsers
  #   value:
  #   - policyArn: arn:aws:iam::aws:policy/AdministratorAccess
  #     secret: addf-mlops-kubeflow-users-user1
  #   - policyArn: arn:aws:iam::aws:policy/AdministratorAccess
  #     secret: addf-mlops-kubeflow-users-user2