[tool.ruff]
line-length = 120
target-version = "py38"
exclude = [
    ".eggs",
    ".git",
    ".hg",
    ".mypy_cache",
    ".tox",
    ".venv",
    ".env",
    "_build",
    "buck-out",
    "build",
    "dist",
    "codeseeder",
]

[tool.ruff.lint]
select = ["F", "I", "E", "W"]
fixable = ["ALL"]

[tool.mypy]
python_version = "3.8"
strict = true
ignore_missing_imports = true
disallow_untyped_decorators = false
exclude = "codeseeder.out/|src/|tests/"

[tool.pytest.ini_options]
addopts = "-v --cov=. --cov-report term"
pythonpath = [
  "."
]

[tool.coverage.run]
omit = ["tests/*", "src"]

[tool.coverage.report]
fail_under = 80
