name: mnist
path: git::https://github.com/awslabs/autonomous-driving-data-framework.git//modules/ml-training/training-image/mnist?ref=release/3.6.0
parameters:
  - name: ecr-repository-name
    valueFrom:
      moduleMetadata:
        group: optionals
        name: ecr-ml-images
        key: EcrRepositoryName
  - name: ecr-repository-arn
    valueFrom:
      moduleMetadata:
        group: optionals
        name: ecr-ml-images
        key: EcrRepositoryArn
  # Base Image = 763104351884.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/pytorch-training:2.1.0-gpu-py310-cu121-ubuntu20.04-ec2:
  - name: base-image-ecr-account-id 
    value: 763104351884
  - name: base-image-name
    value: pytorch-training:2.1.0-gpu-py310-cu121-ubuntu20.04-ec2
