name: lustre-on-eks
path: git::https://github.com/a13zen/autonomous-driving-data-framework.git//modules/integration/fsx-lustre-on-eks?ref=integration-fixes&depth=1
parameters:
  - name: EksClusterAdminRoleArn
    valueFrom:
      moduleMetadata:
        group: core
        name: eks
        key: EksClusterAdminRoleArn
  - name: EksClusterName
    valueFrom:
      moduleMetadata:
        group: core
        name: eks
        key: EksClusterName
  - name: EksOidcArn
    valueFrom:
      moduleMetadata:
        group: core
        name: eks
        key: EksOidcArn
  - name: EksClusterSecurityGroupId
    valueFrom:
      moduleMetadata:
        group: core
        name: eks
        key: EksClusterSecurityGroupId
  - name: Namespace
    value: "training-training"
  - name: FsxFileSystemId
    valueFrom:
      moduleMetadata:
        group: core
        name: fsx-lustre
        key: FSxLustreFileSystemId
  - name: FsxSecurityGroupId
    valueFrom:
      moduleMetadata:
        group: core
        name: fsx-lustre
        key: FSxLustreSecurityGroup
  - name: FsxMountName
    valueFrom:
      moduleMetadata:
        group: core
        name: fsx-lustre
        key: FSxLustreMountName
  - name: FsxDnsName
    valueFrom:
      moduleMetadata:
        group: core
        name: fsx-lustre
        key: FSxLustreAttrDnsName
