AWSTemplateFormatVersion: 2010-09-09
Description: This stack deploys a Module specific IAM permissions

Parameters:
  ProjectName:
    Type: String
    Description: The name of the deployment
  DeploymentName:
    Type: String
    Description: The name of the deployment
  # ModuleName:
  #   Type: String
  #   Description: The name of the Module
  RoleName:
    Type: String
    Description: The name of the IAM Role

Resources:
  Policy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - "s3:Create*"
              - "s3:Put*"
              - "s3:Delete*"
              - "s3:Get*"
              - "s3:List*"
            Effect: Allow
            Resource: 
              - !Sub 
                - "arn:aws:s3:::${ProjectName}*"
                - ProjectName: !Ref ProjectName
              - "arn:aws:s3:::cdk*"
          - Effect: Allow
            Action:
              - "ecr:Describe*"
              - "ecr:Get*"
              - "ecr:List*"
            Resource: '*'
          - Effect: Allow
            Action:
              - "ecr:Create*"
              - "ecr:Delete*"
              - "ecr:*LayerUpload"
              - "ecr:UploadLayerPart"
              - "ecr:Batch*"
              - "ecr:Put*"
            Resource:
              - !Sub "arn:aws:ecr:${AWS::Region}:${AWS::AccountId}:repository/${ProjectName}-${DeploymentName}*"
          - Action:
              - "iam:CreateServiceLinkedRole"
            Effect: Allow
            Resource:
              - !Sub "arn:aws:iam::${AWS::AccountId}:role/aws-service-role/*.amazonaws.com/*"
        Version: 2012-10-17
      PolicyName: !Sub ${ProjectName}-modulespecific-policy
      Roles: [!Ref RoleName]