name: eks
path: modules/core/eks/
parameters:
  - name: vpc-id
    valueFrom:
      moduleMetadata:
        group: optionals
        name: networking
        key: VpcId
  - name: private-subnet-ids
    valueFrom:
      moduleMetadata:
        group: optionals
        name: networking
        key: PrivateSubnetIds
  - name: eks-admin-role-name
    value: Admin
  - name: eks-compute
    value:
      eks_nodegroup_config:
        - eks_ng_name: ng1
          eks_node_quantity: 3
          eks_node_max_quantity: 6
          eks_node_min_quantity: 2
          eks_node_disk_size: 50
          eks_node_instance_types:
            - "m5.large"
        - eks_ng_name: ng2
          eks_node_quantity: 3
          eks_node_max_quantity: 6
          eks_node_min_quantity: 2
          eks_node_disk_size: 50
          eks_node_instance_types:
            - "m5.xlarge"
        - eks_ng_name: gpung1
          eks_node_quantity: 1
          eks_node_max_quantity: 3
          eks_node_min_quantity: 1
          eks_node_disk_size: 100
          eks_node_instance_types:
            - "g4dn.xlarge"
          eks_node_labels:
            usage: visualization
      eks_version: 1.23
      eks_node_spot: False
  - name: eks-addons
    value:
      deploy_aws_lb_controller: True # We deploy it unless set to False
      deploy_external_dns: True # We deploy it unless set to False
      deploy_aws_ebs_csi: True # We deploy it unless set to False
      deploy_aws_efs_csi: True # We deploy it unless set to False
      deploy_aws_fsx_csi: True # We deploy it unless set to False
      deploy_cluster_autoscaler: True # We deploy it unless set to False
      deploy_metrics_server: True # We deploy it unless set to False
      deploy_secretsmanager_csi: True # We deploy it unless set to False
      deploy_external_secrets: False
      deploy_cloudwatch_container_insights_metrics: True # We deploy it unless set to False
      deploy_cloudwatch_container_insights_logs: False
      cloudwatch_container_insights_logs_retention_days: 7
      deploy_amp: False
      deploy_grafana_for_amp: False
---
name: efs
path: modules/core/efs
targetAccount: primary
targetRegion: us-east-1
parameters:
  - name: vpc-id
    valueFrom:
      moduleMetadata:
        group: optionals
        name: networking
        key: VpcId
  - name: removal-policy
    value: DESTROY