name: kubeflow-platform
path: git::https://github.com/awslabs/autonomous-driving-data-framework.git//modules/mlops/kubeflow-platform/
targetAccount: primary
targetRegion: us-east-1
parameters:
  - name: EksClusterMasterRoleArn
    valueFrom:
      moduleMetadata:
        group: core
        name: eks
        key: EksClusterMasterRoleArn
  - name: EksClusterName
    valueFrom:
      moduleMetadata:
        group: core
        name: eks
        key: EksClusterName
  - name: InstallationOption
    value: kustomize
  - name: DeploymentOption
    value: vanilla
  - name: KubeflowReleaseVersion
    value: v1.7.0
  - name: AwsKubeflowBuild
    value: '1.0.3'
