AWSTemplateFormatVersion: 2010-09-09
Description: This template deploys a Module specific IAM permissions

Parameters:
  DeploymentName:
    Type: String
    Description: The name of the deployment
  ModuleName:
    Type: String
    Description: The name of the Module
  RoleName:
    Type: String
    Description: The name of the IAM Role
  TfS3Bucket:
    Type: String
    Description: The name of the Terraform s3 backend bucket
  TfDdbTable:
    Type: String
    Description: The name of the Terraform backend DynamoDB table

Resources:
  Policy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyDocument:
        Statement:
          # Terraform backend specific permissions
          - Action:
              - "s3:List*"
            Effect: Allow
            Resource: 
              - !Sub "arn:aws:s3:::${TfS3Bucket}"
          - Action:
              - "s3:PutObject"
              - "s3:DeleteObject"
              - "s3:GetObject"
            Effect: Allow
            Resource: 
              - !Sub "arn:aws:s3:::${TfS3Bucket}*/${DeploymentName}/${ModuleName}*"
          - Effect: Allow
            Action:
              - "dynamodb:DescribeTable"
              - "dynamodb:GetItem"
              - "dynamodb:PutItem"
              - "dynamodb:DeleteItem"
            Resource: 
              - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${TfDdbTable}"
          # App specific permissions
          - Action:
              - "s3:*"
            Effect: Allow
            Resource: ["arn:aws:s3:::example-tf*"]
        Version: 2012-10-17
      PolicyName: addf-modulespecific-policy
      Roles: [!Ref RoleName]
