AWSTemplateFormatVersion: 2010-09-09
Description: This template deploys a Module specific IAM permissions

Parameters:
  EcrRepositoryArn:
    Type: String
    Description: The ARN of the ECR Repository
  RoleName:
    Type: String
    Description: The name of the IAM Role

Resources:
  Policy:
    Type: "AWS::IAM::Policy"
    Properties:
      Roles: [!Ref RoleName]
      PolicyName: modulespecific-policy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - "ecr:Describe*"
              - "ecr:Get*"
              - "ecr:List*"
              - "ecr:BatchGetImage"
            Resource:
              - !Ref EcrRepositoryArn
              - "arn:aws:ecr:*:*:repository/pytorch-inference*"
          - Effect: Allow
            Action:
              - ecr:*
            Resource:
              - !Ref EcrRepositoryArn
