[tool.ruff]
line-length = 120
target-version = "py38"
exclude = [
    ".eggs",
    ".git",
    ".hg",
    ".mypy_cache",
    ".tox",
    ".venv",
    ".env",
    "_build",
    "buck-out",
    "build",
    "dist",
    "codeseeder",
    "src",
]

[tool.ruff.lint]
select = ["F", "I", "E", "W"]
fixable = ["ALL"]

[tool.coverage.run]
omit = ["tests/*", "src"]

[tool.mypy]
python_version = 3.8
strict = true
ignore_missing_imports = true
allow_untyped_decorators = true
exclude = "codeseeder.out/|src/|tests/"

[tool.pytest.ini_options]
addopts = "-v --cov=. --cov-report term --cov-fail-under=80"
pythonpath = [
  "."
]