version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - cd ml
      - pip install --upgrade --force-reinstall "awscli>1.20.30"
      - pip install -r requirements.txt
  build:
    commands:
      - echo "Updating SageMaker Pipeline"
      - python3 stable_pipeline.py
