name: ros-to-parquet
path: modules/sensor-extraction/ros-to-parquet/
parameters:
  - name: platform
    value: FARGATE
  - name: retries
    value: 1
  - name: timeout-seconds
    value: 3600
  - name: vcpus
    value: 2
  - name: memory-mib
    value: 8192
  - name: full-access-policy-arn
    valueFrom:
      moduleMetadata:
        group: optionals
        name: datalake-buckets
        key: FullAccessPolicyArn
---
name: ros-to-png
path: modules/sensor-extraction/ros-to-png/
parameters:
  - name: platform
    value: EC2
  - name: retries
    value: 1
  - name: timeout-seconds
    value: 3600
  - name: vcpus
    value: 2
  - name: memory-mib
    value: 7168
  - name: resized-width
    value: 1280
  - name: resized-height
    value: 720
  - name: full-access-policy-arn
    valueFrom:
      moduleMetadata:
        group: optionals
        name: datalake-buckets
        key: FullAccessPolicyArn
---
name: object-detection
path: modules/post-processing/yolo-object-detection/
parameters:
  - name: full-access-policy-arn
    valueFrom:
      moduleMetadata:
        group: optionals
        name: datalake-buckets
        key: FullAccessPolicyArn
---
name: lane-detection
path: modules/post-processing/yolop-lane-detection/
parameters:
  - name: full-access-policy-arn
    valueFrom:
      moduleMetadata:
        group: optionals
        name: datalake-buckets
        key: FullAccessPolicyArn