AWSTemplateFormatVersion: 2010-09-09
Description: This stack deploys a Module specific IAM permissions

Parameters:
  ProjectName:
    Type: String
    Description: The name of the Project
  DeploymentName:
    Type: String
    Description: The name of the deployment
  ModuleName:
    Type: String
    Description: The name of the Module
  RoleName:
    Type: String
    Description: The name of the IAM Role

Resources:
  Policy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action:
              - "sts:AssumeRole"
            Resource:
              - !Sub 'arn:aws:iam::${AWS::AccountId}:role/${ProjectName}-${DeploymentName}-${ModuleName}-${AWS::Region}-masterrole'
          - Effect: Allow
            Action:
              - "ssm:GetParameter"
            Resource:
              - "*"
          - Effect: Allow
            Action:
              - "s3:ListBucket"
            Resource:
              - "arn:aws:s3:::*-images-replications-*"
          - Effect: Allow
            Action:
              - "s3:GetObject"
            Resource:
              - "arn:aws:s3:::*-images-replications-*/*"
        Version: 2012-10-17
      PolicyName: "idf-modulespecific-policy"
      Roles: [!Ref RoleName]